language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_eee26a49a0ef_key -iv $encrypted_eee26a49a0ef_iv
  -in ./clasprc.tar.gz.enc -out ./clasprc.tar.gz -d
- tar xvf ./clasprc.tar.gz
- mv ./.gclasprc.json ~/.clasprc.json
install:
- npm install
script:
- clasp pull
- npm run test
