language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_46068108dcef_key -iv $encrypted_46068108dcef_iv
  -in secrets.tar.enc -out ./secrets.tar -d
- tar xvf ./secrets.tar
