language: node_js
node_js:
- node
before_install:
- openssl aes-256-cbc -K $encrypted_46068108dcef_key -iv $encrypted_46068108dcef_iv
  -in gsheetsts-deploy-2527ef095776.json.enc -out ~\/Downloads/gsheetsts-deploy-2527ef095776.json
  -d
